### ISSUE TITLE
check "Variable name "t" doesn't conform to snake_case naming style"

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/kwaciaren#3]
Do we want this one?

I'm personally used to do one-letter variables. I don't have problem with meaningful names on the other hand.

**Comment by jpopelka** [comment]
I don't mind `"t"` or `"fd"` (which also doesn't conform, because the [regexp is](http://pylint-messages.wikidot.com/messages:c0103) `[a-z_][a-z0-9_]{2,30}$`) so +1 to skip this check (C0103).
